- include_vars: "UnixSysAdmin.yml"

- name: Adding Sysadmin Users on Linux Servers
  user:
    name: "{{ item.user }}"
    comment: "{{ item.name }}"
    state: present
    groups: tsadm
    password: "{{ default_password }}"
  with_items: "{{ SettingsUsers }}"

- name: force change password on First Logon
  command: chage -d 0 "{{ item.user }}"
  with_items: "{{ SettingsUsers }}"