- name: Copying the motd file to server
  copy:
    src: /home/fsouza3/ansible/roles/utilities/files/motd
    dest: /etc/
  register: copy_motd_file
  tags: copy_motd_tag

- name: Debug copying the motd file to server
  debug:
    msg: "{{ copy_motd_file }}"


- name: Copying the Linux Checklist script server
  copy:
    src: /home/fsouza3/ansible/roles/utilities/files/chk_list_linux.sh
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0755
  tags: copy_chk_linux
  register: chk_linux_copy

- name: Debug copying the Linux Checklist script server
  debug:
    msg: "{{ chk_linux_copy }}"

- name: Settings chk_list_Linux.sh script in crontab
  cron:
    name: "By Fabiano Prospero | Unix healthcheck script | Log files on path /home/tech/data/checklist"
    user: "root"
    minute: 00
    hour: 23
    job: "/usr/bin/chk_list_linux.sh -g  > /dev/null 2>&1"
  register: Setting_crontab
  tags: Setting_crontab_tag

- name: Debug settings chk_list_Linux.sh script in crontab
  debug:
    msg: "{{ Setting_crontab }}"

- name: Removing the /etc/localtime
  file:
    path: /etc/localtime
    state: absent

- name: Settings TIMEZONE
  file:
    src: /usr/share/zoneinfo/Brazil/East
    dest: /etc/localtime
    owner: root
    group: root
    state: link

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install VNC Server
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tigervnc 
    - libXvnc1 

- name: Stop the Firewall on Server
  service:
    name: firewalld
    state: stopped

- name: Disable the fireall on Server
  service:
    name: firewalld
    state: disabled

- name: Install SAP pkgs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc-c++
    - libstdc++-devel
    - compat-libstdc++-33
    - gcc
    - ksh
    - glibc-devel
    - libaio-devel
    - compat-libcap1-1.10

- name: Copying the sysctl.conf to servers
  copy:
    src: /home/fsouza3/ansible/roles/utilities/files/sysctl.conf
    dest: /etc/

- name: Copying the sysctl.conf to servers
  copy:
    src: /home/fsouza3/ansible/roles/utilities/files/limits.conf
    dest: /etc/security/